{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.4.0.jar",
          "url": "builder-8.4.0.jar",
          "size": 13424139,
          "sha512": "0255216ea2ab8480a1a5642d5adef49884638718769f42c75c7cd99390dd46e5f398fe4311f4019c5842f574316824ff391b428165c57a03078e602728d3f741",
          "sha256": "0171bb226224709aa8d0ab4f3bf3163647ed232ade3a851319dd2126c8934119",
          "sha1": "8aaa522e739c616e216e211d0b82c4c05ed08397",
          "md5": "88329e1c68c2985d7cf808e5f9aeedf1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.4.0.jar",
          "url": "builder-8.4.0.jar",
          "size": 13424139,
          "sha512": "0255216ea2ab8480a1a5642d5adef49884638718769f42c75c7cd99390dd46e5f398fe4311f4019c5842f574316824ff391b428165c57a03078e602728d3f741",
          "sha256": "0171bb226224709aa8d0ab4f3bf3163647ed232ade3a851319dd2126c8934119",
          "sha1": "8aaa522e739c616e216e211d0b82c4c05ed08397",
          "md5": "88329e1c68c2985d7cf808e5f9aeedf1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.4.0-javadoc.jar",
          "url": "builder-8.4.0-javadoc.jar",
          "size": 401060,
          "sha512": "188a869669b20edb220fa4ee53d436a1fb325c20a38bd675b2ce14e99e5246c03f8a6ac26c58317282efb46a8ac74dc069062cf7ad0202e88a80ee7ca4059cb8",
          "sha256": "bba59e0556907b039a786304dcfbfff98440a32f0b312aa8be72b1890ff3a2af",
          "sha1": "58710300cdda601bc15a4fa5a8568d9dce769248",
          "md5": "291f9b9e3fd73cacb8c4f325e869eb9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.4.0-sources.jar",
          "url": "builder-8.4.0-sources.jar",
          "size": 281638,
          "sha512": "f16fe43a888b11f93ea160cfcff5cf9ef46048b6cdf2b46cdec892bc3f06962dad6b1808fad549bb17e0abc528d3a311d0ff441814af3b488ea58e360cbd1a69",
          "sha256": "bf68113090829055c7cb0777fc858c6fbe112a9e19c89fcbc6a639a22b303f15",
          "sha1": "32e29336a4a6bfcbc693f9d158dfbc91ff5ce7f0",
          "md5": "f7725466ef5d9175a7e82038c60fe44a"
        }
      ]
    }
  ]
}
